### ISSUE TITLE
Latest CentOS is not supported.

### ISSUE THREAD

**Issue by qtlin** [cryply/cryply-cli-miner#1]
Nice try making **closed source** miner with forced 5% donation under Ubuntu 16.04.
Definitely no donation from me:
```/tmp/miner-sse4: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/miner-sse4)```

**Comment by cryply** [comment]
Centos famouse for outdated GLIBC.
Fix is to install latest GLIBC and provide path to it in miner.

```
yum groupinstall "Development tools"
cd /tmp 
wget http://ftp.gnu.org/gnu/glibc/glibc-2.18.tar.gz
tar xvzf glibc-2.18.tar.gz
cd glibc-2.18
mkdir glibc-build
cd glibc-build
../configure --prefix='/opt/glibc-2.18'

 nano +179 ../scripts/test-installation.pl
- change  if (/$ld_so_name/) {
- to  if (/\Q$ld_so_name\E/) {
 make
 make install

PATH=/opt/glibc-2.18/bin:$PATH LD_LIBRARY_PATH=/opt/glibc-2.18/lib:/lib64 /opt/glibc-2.18/lib/ld-linux-x86-64.so.2 ./miner-sse4 
--password x --threads 6 --url stratum://pool.cryply.io:3344 --username YourUserName.YourWorkerName

```

**Comment by cryply** [comment]
--threads 6 set for my 8 core server. Good Rule of Thumb is N Cores -1.

**Comment by cryply** [comment]
Miner is 100% written from scratch in RUST by our team. We used 0% of Open Source in it. Team of programmers was working on it few months. Maybe we make it  Open Source  later.

**Comment by cryply** [comment]
Solution:
yum groupinstall "Development tools"
cd /tmp 
wget http://ftp.gnu.org/gnu/glibc/glibc-2.18.tar.gz
tar xvzf glibc-2.18.tar.gz
cd glibc-2.18
mkdir glibc-build
cd glibc-build
../configure --prefix='/opt/glibc-2.18'

 nano +179 ../scripts/test-installation.pl
- change  if (/$ld_so_name/) {
- to  if (/\Q$ld_so_name\E/) {
 make
 make install

PATH=/opt/glibc-2.18/bin:$PATH LD_LIBRARY_PATH=/opt/glibc-2.18/lib:/lib64 /opt/glibc-2.18/lib/ld-linux-x86-64.so.2 ./miner-sse4 
--password x --threads 6 --url stratum://pool.cryply.io:3344 --username YourUserName.YourWorkerName

**Comment by qtlin** [comment]
I may try https://stackoverflow.com/questions/847179/multiple-glibc-libraries-on-a-single-host/851229 later.
Your solution does not seem right because a path to /lib64/ld-linux-x86-64.so.2 is hardcoded in miner and interpreter must match glibc.
