### ISSUE TITLE
a proxy is not supported

### ISSUE THREAD

**Issue by qtlin** [cryply/cryply-cli-miner#2]
invoking with --help shows no proxy support is implemented.

$ /tmp/miner-avx2 --help
Miner 0.2.0

Cryply coin miner.
True Crypto = True Community.
We have created a mining software which will help us give more to each other.
When you are mining - you make Cryply stronger and you encourage those who work hard to never stop.

USAGE:
    miner-avx2 [FLAGS] [OPTIONS] --password <PASSWORD> --username <USER>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
    -v               Sets the level of verbosity

OPTIONS:
    -c, --config <CONFIG>         [env: MINER_CONFIG=]
    -p, --password <PASSWORD>     [env: MINER_PASSWORD=]
    -t, --threads <THREADS>       [env: MINER_THREADS=]  [default: 2]
    -o, --url <URL>               [env: MINER_URL=]  [default: stratum://cryply.luckypool.org:9996]
    -u, --username <USER>         [env: MINER_USER=]

**Comment by cryply** [comment]
Cryply pools on different servers
In different locations
You can use any working pool
or you can use external proxy

**Comment by qtlin** [comment]
I repeat: miner is useless when internet access is only via a proxy. cpuminer can do socks, this miner is completely useless without direct access.
